name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  build_result:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '[]'
outputs:
  build: # output will be available to future steps
    description: 'The current time after waiting'
  unitTest: # output will be available to future steps
    description: 'The current time after waiting'
  codeQuality: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
